#!/usr/bin/env python3
"""Generates Command-Reference.md for the repo-signal GitHub Wiki.

Run from anywhere:
  python3 tools/generate_wiki_command_ref.py

Output: ~/repo-signal.wiki/Command-Reference.md

The command surface is read from `repo_signal.commands`, the single
declaration that `--help`, the unknown-command fallback and the docs checks
all use. This script used to regex-parse the rendered help screen instead,
which made it a fifth hand-maintained view of the same list: it broke silently
when `cli.HELP_TEXT` was replaced by the registry, and `release.sh` reports
that failure only as a skipped step. Reading the registry cannot drift from
it, and a wrapped long command name can no longer drop a row.
"""

import sys
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
WIKI_DIR = Path.home() / "repo-signal.wiki"
OUTPUT = WIKI_DIR / "Command-Reference.md"

sys.path.insert(0, str(REPO_ROOT))

try:
    from repo_signal.commands import COMMANDS
except ImportError:
    print("[error] Could not import repo_signal.commands — run from repo root with the package installed.")
    sys.exit(1)


def usage_lines() -> list[str]:
    lines = [f"repo-signal {line}" for command in COMMANDS for line in command.usage]
    lines.append("repo-signal --help")
    lines.append("repo-signal --version")
    return lines


def write_reference() -> None:
    WIKI_DIR.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Command Reference\n",
        "_Auto-generated by `tools/generate_wiki_command_ref.py` — do not edit manually._\n",
        "\n---\n",
        "## Usage\n",
        "```\n",
    ]
    for line in usage_lines():
        lines.append(f"{line}\n")
    lines += ["```\n", "\n---\n", "## Commands\n"]
    lines += [
        "| Command | Description | Example |\n",
        "|---|---|---|\n",
    ]
    for command in COMMANDS:
        example = f"`repo-signal {command.examples[0]}`" if command.examples else "—"
        lines.append(f"| `{command.name}` | {command.summary} | {example} |\n")

    lines += [
        "\n---\n",
        f"_Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} — {len(COMMANDS)} commands_\n",
    ]

    OUTPUT.write_text("".join(lines), encoding="utf-8")
    print(f"[ok] Written: {OUTPUT}")
    print(f"[ok] Commands: {len(COMMANDS)}")


if __name__ == "__main__":
    if not COMMANDS:
        print("[warn] The command registry is empty — check repo_signal/commands.py")
        sys.exit(1)
    write_reference()
